name: Build Ubuntu Packages ðŸ“¦

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to build from'
        required: true
        type: string

jobs:
  build-ubuntu:
    name: Build Ubuntu ${{ matrix.ubuntu-version }} Package
    runs-on: ubuntu-${{ matrix.ubuntu-version }}.04
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: [22, 24]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-tags: true
        fetch-depth: 0

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential debhelper dh-python python3-setuptools python3-wheel python3-pip pybuild-plugin-pyproject python3-all libpython3-all-dev python3-venv
        python -m pip install build

    - name: Build Python wheel
      run: |
        python -m build --wheel

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc -b
        # Move non-deb relevant files
        mv ../*.changes ~
        mv ../*.buildinfo ~
        # Move and rename deb file to include Ubuntu version
        for file in ../*.deb; do
          if [ -f "$file" ]; then
            base=$(basename "$file" .deb)
            mv "$file" "${HOME}/${base}-ubuntu${{ matrix.ubuntu-version }}.deb"
          fi
        done

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-${{ matrix.ubuntu-version }}-package
        path: |
          ~/*-ubuntu${{ matrix.ubuntu-version }}.deb
          ~/*.changes
          ~/*.buildinfo
